# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NELivePlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NELivePlayerDemo
  pod 'CocoaLumberjack','~> 3.6.1'
  pod 'MJRefresh', '3.7.6'
  pod 'NELivePlayer', '3.2.7'

  target 'NELivePlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NELivePlayerDemoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end
